<nav class="navbar navbar-light fixed-top">
    <a href="<?php echo $this->url->get('admin/index') ?>" class="navbar-brand">
    <img src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="30" height="30" class="d-inline-block align-top"/>
    Cafeteria Kassensystem</a>
    <!-- <a href="<?php echo $this->url->get('admin/overview') ?>" class="nav-item nav-link">Warenübersicht</a>
    <a href="<?php echo $this->url->get('waren/edit') ?>" class="nav-item nav-link">Ware hinzufügen</a>
    <a href="<?php echo $this->url->get('waren/sources') ?>" class="nav-item nav-link mr-auto">Quelle hinzufügen</a> -->
    <?php if ($this->session->has('ausweis')): ?> 
    <div class="dropdown">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <?php echo $this->session->get('ausweis') ?>
        </a>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="<?php echo $this->url->get('index/select') ?>">Bereichswahl</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="<?php echo $this->url->get('logout') ?>">Logout</a>
        </div>
    </div>

    <?php else: ?>
    <a href="<?php echo $this->url->get('index/index') ?>" class="mr-sm-2 nav-item nav-link">Einloggen</a>
    <?php endif ?>
</nav>

<div class="container d-flex flex-column">
    <?php echo $this->getContent(); ?>
</div>