<nav class="navbar navbar-light fixed-top">
    <a href="<?php echo $this->url->get('index/index') ?>" class="navbar-brand">
    <img src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="30" height="30" class="d-inline-block align-top"/>
    Cafeteria Kassensystem</a>

    <a href="<?php echo $this->url->get('index/logout') ?>" class="mr-sm-2 nav-item nav-link">Logout</a>
</nav>

<div class="container d-flex align-items-center ">
    <?php echo $this->getContent(); ?>
</div>