<nav class="navbar navbar-light fixed-top">
    <a href="<?php echo $this->url->get('karten/index') ?>" class="navbar-brand">
    <img src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="30" height="30" class="d-inline-block align-top"/>
    Cafeteria Kassensystem</a>
    <a href="<?php echo $this->url->get('karten/einzahlung') ?>" class="nav-item nav-link">Einzahlung</a>
    <a href="<?php echo $this->url->get('karten/auszahlung') ?>" class="nav-item nav-link">Auszahlung</a>
    <a href="<?php echo $this->url->get('karten/betrag') ?>" class="nav-item nav-link mr-auto">Guthaben</a>
    <a href="<?php echo $this->url->get('logout') ?>" class="mr-sm-2 nav-item nav-link">Logout</a>
</nav>

<div class="container d-flex flex-column">
    <?php echo $this->getContent(); ?>
</div>