<nav class="navbar navbar-light fixed-top">
    <a href="<?php echo $this->url->get('waren/index') ?>" class="navbar-brand">
    <img src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="30" height="30" class="d-inline-block align-top"/>
    Cafeteria Kassensystem</a>
    <a href="<?php echo $this->url->get('waren/overview') ?>" class="nav-item nav-link">Warenübersicht</a>
    <a href="<?php echo $this->url->get('waren/edit') ?>" class="nav-item nav-link">Ware hinzufügen</a>
    <a href="<?php echo $this->url->get('waren/sources') ?>" class="nav-item nav-link mr-auto">Quelle hinzufügen</a>
    <a href="<?php echo $this->url->get('logout') ?>" class="mr-sm-2 nav-item nav-link">Logout</a>
</nav>

<div class="container d-flex flex-column">
    <?php echo $this->getContent(); ?>
</div>