<?php

/**
 * Kartentransaktionen
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-06-25, 11:56:28
 */
class Kartentransaktionen extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $trans_id;

    /**
     *
     * @var string
     */
    public $user;

    /**
     *
     * @var string
     */
    public $vertreter;

    /**
     *
     * @var double
     */
    public $amount;

    /**
     *
     * @var string
     */
    public $datetime;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("kassensystem");
        $this->setSource("kartentransaktionen");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'kartentransaktionen';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Kartentransaktionen[]|Kartentransaktionen|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Kartentransaktionen|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
