<?php

/**
 * Log
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-06-24, 16:01:03
 */
class Log extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $entry;

    /**
     *
     * @var string
     */
    public $exec_user;

    /**
     *
     * @var integer
     */
    public $action;

    /**
     *
     * @var string
     */
    public $what;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("kassensystem");
        $this->setSource("log");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'log';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Log[]|Log|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Log|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
