<?php

/**
 * Transaktionen
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-06-25, 15:06:44
 */
class Transaktionen extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $trans_id;

    /**
     *
     * @var string
     */
    public $user;

    /**
     *
     * @var string
     */
    public $datetime;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("kassensystem");
        $this->setSource("transaktionen");
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'transaktionen';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Transaktionen[]|Transaktionen|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Transaktionen|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
