<?php

/**
 * Warentransaktionen
 * 
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-06-25, 15:07:06
 */
class Warentransaktionen extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var integer
     */
    public $trans_id;

    /**
     *
     * @var integer
     */
    public $waren_id;

    /**
     *
     * @var integer
     */
    public $revision;

    /**
     *
     * @var integer
     */
    public $menge;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("kassensystem");
        $this->setSource("warentransaktionen");
    }


    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'warentransaktionen';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Warentransaktionen[]|Warentransaktionen|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Warentransaktionen|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }


    /**
     * Returns all Transactions since the val
     * @var dt The Datetime
     * @return false|array['id','user','vertreter','datetime','price','tax']
     */
    public function getSalesSince($dt = 0) {
        return $this->modelsManager->executeQuery("SELECT waren_id, SUM(menge) AS menge
        FROM Transaktionen, Warentransaktionen, Warenrevisionen
        WHERE Transaktionen.trans_id = Warentransaktionen.trans_id AND waren_id = id 
        AND Warentransaktionen.revision = Warenrevisionen.revision AND datetime >= :dt:
        GROUP BY waren_id
        ORDER BY menge DESC",
        ['dt' => $dt]);
    }

}
