<?php

/**
 * Warenrevisionen
 * 
 * @package test
 * @autogenerated by Phalcon Developer Tools
 * @date 2018-07-11, 08:47:15
 */
class Warenrevisionen extends \Phalcon\Mvc\Model
{

    /**
     *
     * @var string
     */
    public $id;

    /**
     *
     * @var integer
     */
    public $revision;

    /**
     *
     * @var double
     */
    public $price;

    /**
     *
     * @var integer
     */
    public $mehrwertsteuer_voll;

    /**
     *
     * @var string
     */
    public $description;

    /**
     *
     * @var integer
     */
    public $source;

    /**
     *
     * @var double
     */
    public $s_price;

    /**
     *
     * @var integer
     */
    public $s_mwst_full;

    /**
     *
     * @var string
     */
    public $created;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("kassensystem");
        $this->setSource("warenrevisionen");
        $this->belongsTo('id', 'test\Waren', 'id', ['alias' => 'Waren']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'warenrevisionen';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return Warenrevisionen[]|Warenrevisionen|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return Warenrevisionen|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
