<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Roro Kassensystem</title>
        
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/roroPay.svg')?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/bootstrap.min.css') ?>"/>
        <link rel="stylesheet" href="<?php echo $this->url->get('css/floating-labels.css') ?>"/>
    </head>
    <body class="d-flex" style="flex-direction: column">
        <script src="<?php echo $this->url->get('js/jquery-3.3.1.min.js'); ?>"></script>
        <?php echo $this->getContent(); ?>
        
        <script src="<?php echo $this->url->get('js/bootstrap.bundle.min.js'); ?>"></script>
    </body>
</html>
