<?php
    echo $this->tag->form(
        [
            "",
            "autocomplete" => "off",
            "class" => "form-signin"
        ]
    );
?>

<div class="text-center mb-4">
    <img class="mb-4" src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="72" height="72" />
    <h2>Cafeteria Kassensystem</h1>
    <p class="lead">
        Bitte einloggen.
    </p>
    <?php echo $this->getContent() ?>
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["ausweis", "size" => 16, "required" => "", "class" => "form-control", "id" => "fieldAusweis", "placeholder" => "Ausweisnummer", "autofocus" => ""]) ?>
    <label for="fieldAusweis">Ausweisnummer</label>
</div>

<div class="form-label-group">
    <?php echo $this->tag->passwordField(["pw", "class" => "form-control", "required" => "", "id" => "pw", "placeholder" => "Passwort"]) ?>
    <label for="pw">Passwort</label>
</div>

    <?php echo $this->tag->submitButton(["Einloggen", "class" => "btn btn-lg btn-primary btn-block"]) ?>

<?php echo $this->tag->endForm(); ?>

