
CREATE TABLE `kassensystem`.`users` ( `ausweis` BIGINT(13) UNSIGNED NOT NULL , `amount` FLOAT(5) UNSIGNED NOT NULL DEFAULT '0' , `pw` VARCHAR(60) NULL DEFAULT NULL , `access` TINYINT UNSIGNED NULL DEFAULT NULL , PRIMARY KEY (`ausweis`)) ENGINE = InnoDB;
