<?php
    echo $this->tag->form(
        [
            "waren/doDelete/$id",
            "autocomplete" => "off",
            "class" => "form-signin"
        ]
    );
?>

<div class="text-center mb-4">
    <img class="mb-4" src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="72" height="72" />
    <h2>Cafeteria Kassensystem</h1>
    <p class="lead">
        Soll die Ware (<?php echo $id ?>) gelöscht werden?
    </p>
    <?php echo $this->getContent() ?>
</div>
<div class="btn-group d-flex">
    <?php echo $this->tag->submitButton(["Löschen", "class" => "btn btn-lg btn-danger flex-fill"]);
    echo $this->tag->linkTo(["waren/overview/", "Abbrechen", "class" => "btn btn-lg btn-primary flex-fill"]);
    ?>
</div>
<?php echo $this->tag->endForm(); ?>
