<div class="row">
<?php 
echo $this->getContent();
echo $this->tag->form(["", "class" => "form-signin"]); ?>
<div class="form-label-group">
    <?php echo $this->tag->textField(["id", "size" => 40, "id" => "id", "class" => "form-control", "placeholder" => "Warennummer", "required" => "", "autofocus" => "", "value" => $id]) ?>
    <label for="id">Warennummer</label>
</div>
<div class="form-label-group">
    <?php echo $this->tag->textField(["produkt", "size" => 500, "id" => "produkt", "class" => "form-control", "placeholder" => "Produkt", "required" => "", "value" => $description]) ?>
    <label for="produkt">Produkt</label>
</div>

<div class="form-label-group">
    <?php echo $this->tag->select(["source", $sources, "class" => "form-control", "active" => 10]) ?>
    
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["preis", "size" => 6, "id" => "preis", "class" => "form-control", "placeholder" => "Preis", "required" => "", "value" => $s_price]) ?>
    <label for="preis">Einkaufspreis</label>
</div>
<div class="custom-control custom-checkbox form-group">
    <input type="checkbox" name="mwst" id="mwst" class="custom-control-input" <?php if ($s_mwst_full) echo "checked" ?>>
    <label for="mwst" class="custom-control-label">19% Mehrwertsteuer?</label>
</div>
<hr>
<div class="form-label-group">
    <?php echo $this->tag->textField(["preis", "size" => 6, "id" => "preis", "class" => "form-control", "placeholder" => "Preis", "required" => "", "value" => $price]) ?>
    <label for="preis">Verkaufspreis</label>
</div>
<div class="custom-control custom-checkbox form-group">
    <input type="checkbox" name="mwst" id="mwst" class="custom-control-input" <?php if ($mwst) echo "checked" ?>>
    <label for="mwst" class="custom-control-label">19% Mehrwertsteuer?</label>
</div>
<div class="btn-group btn-group-lg d-flex">
    <?php echo $this->tag->linkTo(["waren", "Abbrechen", "class" => "btn btn-danger flex-fill"]);
    echo $this->tag->submitButton(["Speichern", "class" => "btn btn-success flex-fill"]) ?>
</div>
</div>