<?php
    echo $this->tag->form(
        [
            "waren/",
            "autocomplete" => "off",
            "class" => "form-signin"
        ]
    );
?>

<div class="text-center mb-4">
    <img class="mb-4" src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="72" height="72" />
    <h2>Cafeteria Kassensystem</h1>
    <p class="lead">
        Bitte eine Aktion wählen.
    </p>
    <?php echo $this->getContent() ?>
</div>

    <?php echo $this->tag->linkTo(["waren/overview/", "Warenübersicht", "class" => "btn btn-lg btn-success btn-block"]);
    echo $this->tag->linkTo(["waren/edit/", "Waren hinzufügen", "class" => "btn btn-lg btn-danger btn-block"]);
    echo $this->tag->linkTo(["waren/sources/", "Quelle hinzufügen", "class" => "btn btn-lg btn-primary btn-block"]);   
    echo $this->tag->linkTo(["waren/salesSince/", "Verkäufe", "class" => "btn btn-lg btn-secondary btn-block"]);   
    
    ?>

<?php echo $this->tag->endForm(); ?>
