<?php
    echo $this->getContent();
    echo $this->tag->form([
        'waren/overview',
        'class' => 'form form-inline'
    ]);
?>
<div class="input-group" style="margin-bottom: 1rem">
<div class="form-label-group input-group-prepend" style="margin-bottom: 0rem">
    <?php echo $this->tag->textField(["id", "class" => "form-control", "id" => "waren_id", "size" => 40, "placeholder" => "Warennummer", "autofocus" => ""]); ?>
    <label for="waren_id">Warennummer</label>
</div>
<div class="input-group-append">
<?php echo $this->tag->submitButton(["Suchen", "class"=> "btn btn-lg btn-primary"]); 
    echo "</div></div>";
    echo $this->tag->endForm();
?>
<table class="table table-hover">
    <thead>
        <tr><th>Warennummer</th><th>Produkt</th><th>Quelle</th><th>Einkaufspreis</th><th>Verkaufspreis</th><th>Aktionen</th></tr>
    </thead>
    <tbody>
        <?php foreach($page->items as $ware): if ($ware->deleted) continue; ?>
        <tr <?php if ($ware->deleted) echo "class=\"table-secondary\"" ?>><th><?php echo $ware->id ?></td>
            <td><?php echo $ware->description ?></td>
            <td><?php echo $ware->name ?></td>
            <td><?php echo str_replace('.', ',', round($ware->s_price * ($ware->s_mwst_full ? 1.19 : 1.07), 2))." Euro<br>inkl. "; if ($ware->s_mwst_full) echo "19%"; else echo "7%"; echo " MwSt." ?></td>
            <td><?php echo str_replace('.', ',', round($ware->price * ($ware->mehrwertsteuer_voll ? 1.19 : 1.07), 2))." Euro<br>inkl. "; if ($ware->mehrwertsteuer_voll) echo "19%"; else echo "7%"; echo " MwSt." ?></td>
            <td><div class="btn-group">
            <?php echo $this->tag->linkTo(["waren/edit/$ware->id", "Bearbeiten", "class" => "btn btn-sm btn-outline-warning"]);
                echo $this->tag->linkTo(["waren/delete/$ware->id", "Löschen", "class" => "btn btn-sm btn-outline-danger"]);
            ?>
            </div>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>
<div class="d-flex flex-row">
<nav class="mx-auto">
    <ul class="pagination" style="margin-bottom: 0">
      <li class="page-item">
      <?php echo $this->tag->linkTo(["waren/overview/$page->before/$perPage", "<span aria-hidden=\"true\">&laquo;</span>
          <span class=\"sr-only\">Previous</span>", "class" => "page-link"]) ?>
      </li>
      <?php if ($page->current != $page->before): ?>
      <li class="page-item"><?php echo $this->tag->linkTo(["waren/overview/$page->before/$perPage", "$page->before", "class" => "page-link"]) ?></li>
      <?php endif ?>
      <li class="page-item active"><?php echo $this->tag->linkTo(["waren/overview/$page->current/$perPage", "$page->current", "class" => "page-link"]) ?></li>
      <?php if ($page->current != $page->next): ?>
      <li class="page-item"><?php echo $this->tag->linkTo(["waren/overview/$page->next/$perPage", "$page->next", "class" => "page-link"]) ?></li>
      <?php endif ?>
      <li class="page-item">
      <?php echo $this->tag->linkTo(["waren/overview/$page->next/$perPage", "<span aria-hidden=\"true\">&raquo;</span>
          <span class=\"sr-only\">Next</span>", "class" => "page-link"]) ?>
      </li>
    </ul>
</nav>
<?php echo $this->tag->linkTo(["waren/edit/", "Ware hinzufügen", "class" => "btn btn-danger"]); ?>
</div>