<div class="d-print-none">
<?php
    echo $this->getContent();
    echo $this->tag->form([
        'waren/salesSince/',
        'class' => 'form form-inline'
    ]);
?>
<div class="input-group" style="margin-bottom: 1rem">
<div class="form-label-group input-group-prepend" style="margin-bottom: 0rem">
    <input type="date" class="form-control" name="dt" id="dt"/>
    <label for="dt">frühester Zeitpunkt</label>
</div>
    <input type="time" class="form-control" name="t" id="t"/>
<div class="input-group-append">
<?php echo $this->tag->submitButton(["Ausgeben", "class"=> "btn btn-lg btn-primary"]); 
    echo "</div></div>";
    echo $this->tag->endForm();
?>
</div>

<table class="table table-sm table-hover">
    <thead>
        <tr><th>Warennummer</th><th>Menge</th></tr>
    </thead>
    <tbody>
        <?php foreach($data as $i): ?>
        <tr><th><?php echo $i->waren_id ?></td><td><?php echo $i->menge ?></tr>
        <?php endforeach ?>
    </tbody>
</table>