<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php
    echo $this->tag->form(
        [
            "users/search",
            "autocomplete" => "off",
            "class" => "form-signin"
        ]
    );
?>

<div class="text-center mb-4">
    <img class="mb-4" src="<?php $this->url->get('img/roroPay.svg'); ?>" alt ="" width="72" height="72" />
    <h1 class="display-4">Search users</h1>
    <p class="lead">
        <?php echo $this->tag->linkTo(["users/new", "Create users"]) ?>
    </p>
    <?php echo $this->getContent() ?>
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["ausweis", "size" => 16, "class" => "form-control", "id" => "fieldAusweis", "placeholder" => "Ausweisnummer"]) ?>
    <label for="fieldAusweis">Ausweisnummer</label>
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["amount", "size" => 30, "class" => "form-control", "id" => "fieldAmount", "placeholder" => "Betrag"]) ?>
    <label for="fieldAmount">Betrag</label>
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["pw", "size" => 30, "class" => "form-control", "id" => "fieldPw", "placeholder" => "Passwort"]) ?>
    <label for="fieldPw">Passwort</label>
</div>

<div class="form-label-group">
    <?php echo $this->tag->textField(["access", "type" => "number", "class" => "form-control", "id" => "fieldAccess", "placeholder" => "Access"]) ?>
    <label for="fieldAccess">Access</label>
</div>

    <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-lg btn-primary btn-block"]) ?>

<?php echo $this->tag->endForm(); ?>
