<div class="row">

<?php
    echo $this->getContent();
    echo $this->tag->form([
        "cashier/add/$page->current/0/$perPage/",
        'class' => 'form form-inline'
    ]);
?>
<div class="input-group" style="margin-bottom: 1rem">
<div class="form-label-group input-group-right input-group" style="margin-bottom: 0rem">
    <?php echo $this->tag->textField(["menge", "class" => "form-control", "id" => "menge", "size" => 40, "placeholder" => "Menge", "autofocus" => ""]); ?>
    <label for="menge">Menge</label>
</div>
<div class="form-label-group input-group-left" style="margin-bottom: 0rem">
    <?php echo $this->tag->textField(["id", "class" => "form-control", "id" => "waren_id", "size" => 40, "placeholder" => "Warennummer", "required" => ""]); ?>
    <label for="waren_id">Warennummer</label>
</div>
<div class="input-group-append btn-group">
<?php echo $this->tag->submitButton(["Hinzufügen", "class"=> "btn btn-lg btn-primary"]); 
    echo $this->tag->linkTo(["cashier/check", "Zahlen", "class" => "btn btn-lg btn-danger"]);
    echo "</div></div>";
    echo $this->tag->endForm();
?>
</div>
<div class="row">
    <table class="table table-hover table-sm">
        <thead>
            <tr><th>Warennummer</th><th>Produkt</th><th>Menge</th><th>Preis</th><th>Aktionen</th></tr>
        </thead>
        <tbody>
            <?php foreach($page->items as $ware): ?>
            <tr><th><?php echo $ware['id'] ?></td>
                <td><?php echo $ware['description'] ?></td>
                <td><?php echo $ware['menge'] ?></td>
                <td><?php echo str_replace('.', ',', round($ware['price'] * ($ware['mehrwertsteuer_voll'] ? 1.19 : 1.07), 2))."€ "; if ($ware['mehrwertsteuer_voll']) echo "A"; else echo "B"; ?></td>
                <td><div class="btn-group">
                <?php echo $this->tag->linkTo(["cashier/delete/".$ware['id']."/$page->current/$perPage", "Löschen", "class" => "btn btn-sm btn-outline-danger"]);
                ?>
                </div>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
        <tfoot>
            <tr><td></td><td></td><td></td><td></td><td></td></tr>
            <tr><th>MwSt</th><th>Netto</th><th>Steuer</th><th>Brutto</th></tr>
            <tr><th>Summe</th><td><?php echo str_replace('.', ',', $n) ?></td><td><?php echo str_replace('.', ',', $s) ?></td><td><?php echo str_replace('.', ',', $b) ?></td></tr>
        </tfoot>
    </table>
    <div class="row justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li class="page-item">
              <?php echo $this->tag->linkTo(["cashier/add/$page->before/0/$perPage", "<span aria-hidden=\"true\">&laquo;</span>
                  <span class=\"sr-only\">Previous</span>", "class" => "page-link"]) ?>
              </li>
              <?php if ($page->current != $page->before): ?>
              <li class="page-item"><?php echo $this->tag->linkTo(["cashier/add/$page->before/0/$perPage", "$page->before", "class" => "page-link"]) ?></li>
              <?php endif ?>
              <li class="page-item active"><?php echo $this->tag->linkTo(["cashier/add/$page->current/0/$perPage", "$page->current/$page->last", "class" => "page-link"]) ?></li>
              <?php if ($page->current != $page->next AND $page->next != 0): ?>
              <li class="page-item"><?php echo $this->tag->linkTo(["cashier/add/$page->next/0/$perPage", "$page->next", "class" => "page-link"]) ?></li>
              <?php endif ?>
              <li class="page-item">
              <?php echo $this->tag->linkTo(["cashier/add/$page->next/0/$perPage", "<span aria-hidden=\"true\">&raquo;</span>
                  <span class=\"sr-only\">Next</span>", "class" => "page-link"]) ?>
              </li>
            </ul>
        </nav>
    </div>
</div>