<div class="row">
    <?php echo $this->getContent() ?>
    <table class="table table-hover">
        <thead>
            <tr><th>Warennummer</th><th>Produkt</th><th>Preis</th><th>Aktionen</th></tr>
        </thead>
        <tbody>
            <?php foreach($page->items as $ware): ?>
            <tr><th><?php echo $ware->id ?></td>
                <td><?php echo $ware->description ?></td>
                <td><?php echo str_replace('.', ',', $ware->price)."€ "; if ($ware->mehrwertsteuer_voll) echo "A"; else echo "B"; ?></td>
                <td><div class="btn-group">
                <?php echo $this->tag->linkTo(["cashier/delete/$ware->id/$page->current/$perPage", "Löschen", "class" => "btn btn-sm btn-outline-danger"]);
                ?>
                </div>
                </td>
            </tr>
            <?php endforeach ?>
        </tbody>
    	<tfoot>
        <tr><th>A: 19 % MwSt.</th><th>B: 7 % MwSt.</th><th>Endpreis</th><th>MwSt. Beträge</th></tr>
        </tfoot>
    </table>
</div>
    <div class="row float-right">
<?php echo $this->tag->linkTo(["cashier/checkout/", "Zahlen", "class" => "btn btn-lg btn-primary"]) ?>
</div>
    <div class="row justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li class="page-item">
              <?php echo $this->tag->linkTo(["cashier/check/$page->before/$perPage", "<span aria-hidden=\"true\">&laquo;</span>
                  <span class=\"sr-only\">Previous</span>", "class" => "page-link"]) ?>
              </li>
              <?php if ($page->current != $page->before): ?>
              <li class="page-item"><?php echo $this->tag->linkTo(["cashier/check/$page->before/$perPage", "$page->before", "class" => "page-link"]) ?></li>
              <?php endif ?>
              <li class="page-item active"><?php echo $this->tag->linkTo(["cashier/check/$page->current/$perPage", "$page->current/$page->last", "class" => "page-link"]) ?></li>
              <?php if ($page->current != $page->next): ?>
              <li class="page-item"><?php echo $this->tag->linkTo(["cashier/check/$page->next/$perPage", "$page->next", "class" => "page-link"]) ?></li>
              <?php endif ?>
              <li class="page-item">
              <?php echo $this->tag->linkTo(["cashier/check/$page->next/$perPage", "<span aria-hidden=\"true\">&raquo;</span>
                  <span class=\"sr-only\">Next</span>", "class" => "page-link"]) ?>
              </li>
            </ul>
        </nav>
    </div>
