<?php
    echo $this->tag->form(
        [
            "cashier/",
            "autocomplete" => "off",
            "class" => "form-signin"
        ]
    );
?>

<div class="text-center mb-4">
    <img class="mb-4" src="<?php echo $this->url->get('img/roroPay.svg'); ?>" alt ="" width="72" height="72" />
    <h2>Cafeteria Kassensystem</h1>
    <p class="lead">
        Bitte eine Aktion wählen.
    </p>
    <?php echo $this->getContent() ?>
</div>

    <?php 
    echo $this->tag->linkTo(["cashier/add/1/10/true", "Aktueller Kassiervorgang", "class" => "btn btn-lg btn-success btn-block"]);   
    echo $this->tag->linkTo(["cashier/add/1/10/true", "Neuer Kassiervorgang", "class" => "btn btn-lg btn-secondary btn-block"]);   
    ?>

<?php echo $this->tag->endForm(); ?>
