<div class="d-print-none">
<?php
    echo $this->getContent();
    echo $this->tag->form([
        'cashier/transactions',
        'class' => 'form form-inline'
    ]);
?>
<div class="input-group" style="margin-bottom: 1rem">
<div class="form-label-group input-group-prepend" style="margin-bottom: 0rem">
    <input type="text" class="form-control" name="userid" id="userid" placeholder="Kartennummer"/>
    <label for="userid">Kartennummer</label>
</div>
<div class="input-group-append">
<?php echo $this->tag->submitButton(["Ausgeben", "class"=> "btn btn-lg btn-primary"]); 
    echo "</div></div>";
    echo $this->tag->endForm();
?>
</div>

<table class="table table-hover table-sm">
    <thead>
        <tr><th>Transaktion</th><th>Kunde</th><th>Verkäufer</th><th>Preis</th><th>Steuern</th><th>Datum und Uhrzeit</th></tr>
    </thead>
    <tbody>
        <?php foreach($t as $transaction): ?>
        <tr>
            <th><?php echo $transaction['id'] ?></th>
            <td><?php echo $transaction['user'] ?></td>
            <td><?php echo $transaction['vertreter'] ?></td>
            <td><?php echo $transaction['price'] ?></td>
            <td><?php echo $transaction['tax'] ?></td>
            <td><?php echo $transaction['datetime'] ?></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>